const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ratios={"1:1":{low:[768,768],standard:[1024,1024],high:[1280,1280]},"2:3":{low:[640,960],standard:[768,1152],high:[896,1344]},"3:2":{low:[960,640],standard:[1152,768],high:[1344,896]},"3:4":{low:[672,896],standard:[768,1024],high:[864,1152]},"4:3":{low:[896,672],standard:[1024,768],high:[1152,864]},"9:16":{low:[576,1024],standard:[720,1280],high:[864,1536]},"16:9":{low:[1024,576],standard:[1280,720],high:[1536,864]},"21:9":{low:[1344,576],standard:[1792,768],high:[2016,864]}};
const notes={T2VA:"无需参考图片，完全根据文字构建视频。",I2VA:"至少上传1张首帧图；第一张图将在0秒完整对齐。",FL2VA:"必须正好上传2张图：第一张首帧，第二张尾帧。",L2VA:"至少上传1张尾帧图；视频最终收束到第一张图。",Ref2VA:"上传1至12张完整参考图，并填写人物、产品、场景或风格用途。",Hybrid:"关键帧与参考媒体混合：至少一个首帧/尾帧关键帧，再添加参考图或参考声音。"};
const notesEn={T2VA:"No reference image is required; build the video entirely from text.",I2VA:"Upload at least one first-frame image; Picture 1 is aligned to 0 seconds.",FL2VA:"Upload exactly two images: the first frame and the last frame.",L2VA:"Upload at least one last-frame image; the video resolves to Picture 1.",Ref2VA:"Upload 1–12 complete references and describe each character, product, scene, or style.",Hybrid:"Mix keyframes with reference media: add a first/last keyframe plus another image or audio reference."};
const builtinTemplates=[
 {id:"cinematic",name:"电影叙事",idea:"主体在明确场景中完成一段连续、有起承转合的动作。镜头从环境建立，推进到动作特写，最后以清晰结果收束。",style:"cinematic photorealism, controlled lighting, coherent motion"},
 {id:"ad",name:"产品广告",idea:"展示产品外观、使用过程、核心卖点和最终行动号召。画面简洁高级，产品始终清晰。",style:"premium commercial, clean composition, product hero lighting"},
 {id:"action",name:"动作战斗",idea:"两名角色进行连贯高速对决，攻防关系清楚，最后出现决定性必杀技与结果镜头。",style:"dynamic action cinematography, readable choreography, impact frames"},
 {id:"meme",name:"夸张表情短片",idea:"角色以适合情境的夸张表情和肢体动作完成表演，配合弹性形变、快速推拉和喜剧音效。",style:"exaggerated comic acting, meme timing, elastic cartoon effects"}
];
const builtinSkills=[
 {id:"skill-abstract-expression",name:"abstract-expression-video-prompter",description:"为短视频选择与情境相关的漫剧/表情包演技、弹性形变、喜剧节奏和同步音效。",source:"内置适配 · Codex Skill",instructions:`Keep the referenced character identity, clothing, camera direction, and environment stable. Build one continuous emotional arc: neutral setup -> clear trigger -> readable reaction -> exaggerated transformation -> short hold -> recovery or punchline. Choose only effects that directly fit the scene, with at most three effects in one clip. Available effect families include eye-pop shock, star or heart eyes, puffed cheeks, facial melting, brain smoke, misplaced facial features, galaxy dizziness, mouth zipper, waterfall tears, soul leaving body, stone embarrassment, toe-curling embarrassment, blooming flowers, head fire, exploding hair, stone shock, shoulder mini-characters fighting, coin eyes, drool river, eating glow, "true fragrance" reversal, speed slap, gacha frenzy, slacking guilt, stubbornness, and lemon-sour reaction. Synchronize squash-and-stretch, camera punches, freeze beats, particles, and comic sound effects. Keep it funny and expressive, never grotesque or horror.`},
 {id:"skill-brand-promo",name:"brand-promo-video-generator",description:"根据真实品牌、产品和店面素材设计清晰卖点、镜头节奏与行动号召，避免虚构宣传。",source:"内置适配 · MiniMax Skill",instructions:`Treat supplied logos, product images, screenshots, store images, and user-provided claims as authoritative. Do not invent product features, prices, guarantees, UI states, awards, or performance claims. Preserve brand marks, product shape, colors, labels, and logo clearspace. Use a product-specific story spine: recognizable opening, customer need or context, product/service evidence, payoff, and a clear call to action. Map each spoken claim to a visible supporting action or asset. Keep shots readable, commercially polished, and executable within the allotted duration. Avoid fake HUD overlays, fake interface screens, unreadable text, and decorative effects that obscure the product or CTA.`},
 {id:"skill-paper-collage",name:"paper-collage-explainer-generator",description:"把概念转成高级纸张拼贴、半色调剪纸和逐件组装的定格动画说明风格。",source:"内置适配 · MiniMax Skill",instructions:`Use premium editorial paper collage on a flat bold color field: black-and-white halftone cutouts, solid cardstock accents, cream keylines, subtle paper fiber, restrained torn edges, and small grounding shadows. Animate as tactile stop-motion assembly: paper pieces pop in, slide, bounce, press, layer, and lock into place with visible depth. Translate each idea into one clear visual metaphor and keep the layout legible. Default audio is tactile collage sound effects only—paper pops, page flips, clicks, swishes, snaps, and soft impacts. Add voiceover, subtitles, or background music only when explicitly requested. Do not fabricate UI, logos, quotations, or long unreadable text.`}
];
const zh={generate:"生成 H3 提示词",stop:"停止",project:"未命名项目"};
const en={generate:"Generate H3 Prompt",stop:"Stop",project:"Untitled project",subtitle:"Local multimodal AI · offline prompt workstation",history:"History",templates:"Templates",settings:"Settings",checking:"Checking Ollama",newProject:"New",saveProject:"Save project",export:"Export",import:"Import",mode:"Generation mode",modeHelp:"Choose an H3 task type",t2va:"Text to video",i2va:"First frame to video",fl2va:"First/last frames",l2va:"Last frame to video",ref2va:"Full references",creative:"Creative brief",creativeHelp:"Scene, characters, actions, dialogue, style and sound",apply:"Apply",clear:"Clear",chooseImages:"Choose or drop reference images",imageLimit:"PNG / JPG / WEBP · up to 12",canvasTime:"Canvas & timing",canvasTimeHelp:"Ratio, size and segments",width:"Width",height:"Height",quality:"Quality preset",low:"Low VRAM",standard:"Standard",high:"High quality",segments:"Segment count",secondsPer:"Seconds each",total:"Total duration",seconds:"seconds",advanced:"Advanced",language:"Dialogue language",promptOutputLanguage:"H3 prompt output language",scriptOutputLanguage:"Script output language",standardH3English:"English (H3 standard, recommended)",translatedChinese:"Chinese description (nonstandard translation)",followInput:"Follow input",style:"Visual style",music:"Music",sound:"Sound effects",negative:"Negative constraints",context:"Context length",result:"Result",model:"AI model",waiting:"Waiting",copySegment:"Copy segment",copyAll:"Copy all",download:"Download TXT",generating:"Local model is analyzing and writing",generatingHelp:"Watch the stream or stop at any time",offline:"Offline mode",offlineHelp:"Images are only sent to your configured Ollama endpoint.",changelog:"Changelog",ollamaAddress:"Ollama endpoint",test:"Test connection",save:"Save",historyProjects:"Projects & history",templateManager:"Template manager",saveTemplate:"Save as template"};
let mode="T2VA",workflow="direct",ratio="16:9",images=[],audios=[],aborter=null,scriptAborter=null,fullOutput="",segments=[],activeSegment=-1,settings=JSON.parse(localStorage.getItem("h3.settings")||"{}"),uiLang=settings.language||"zh",selectedSkillIds=JSON.parse(localStorage.getItem("h3.selectedSkills")||"[]");
const originalTexts=new Map($$('[data-i18n]').map(el=>[el,el.textContent]));
let colorTheme=settings.theme||"dark";
const dbp=new Promise((resolve,reject)=>{const q=indexedDB.open("h3-prompt-studio",1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains("projects"))d.createObjectStore("projects",{keyPath:"id"});if(!d.objectStoreNames.contains("history"))d.createObjectStore("history",{keyPath:"id"})};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});
async function dbPut(store,value){const d=await dbp;return new Promise((res,rej)=>{const q=d.transaction(store,"readwrite").objectStore(store).put(value);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
async function dbAll(store){const d=await dbp;return new Promise((res,rej)=>{const q=d.transaction(store).objectStore(store).getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbDelete(store,id){const d=await dbp;return new Promise((res,rej)=>{const q=d.transaction(store,"readwrite").objectStore(store).delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
function escapeHtml(s=""){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const backendDefaults={ollama:"http://127.0.0.1:11434",lmstudio:"http://127.0.0.1:1234/v1",llamacpp:"http://127.0.0.1:8080/v1",openai:"http://127.0.0.1:8000/v1"};
function backendType(){return settings.backend||"ollama"}
function endpoint(){return (settings.baseUrl||settings.ollamaUrl||backendDefaults[backendType()]).replace(/\/$/,"")}
function api(path){const q=new URLSearchParams({backend:backendType(),baseUrl:endpoint(),apiKey:settings.apiKey||""});return path+(path.includes("?")?"&":"?")+q.toString()}
function toast(msg){const el=$("#validation");el.className="validation good";el.textContent=msg}
function applyI18n(){const isEn=uiLang==="en",set=(selector,cn,enText)=>{const el=$(selector);if(el)el.textContent=isEn?enText:cn};document.documentElement.lang=isEn?"en":"zh-CN";$("#langBtn").textContent=isEn?"中":"EN";$$('[data-i18n]').forEach(el=>{el.textContent=isEn?(en[el.dataset.i18n]||originalTexts.get(el)):originalTexts.get(el)});$$('[data-i18n-placeholder]').forEach(el=>{if(!el.dataset.zhPlaceholder)el.dataset.zhPlaceholder=el.getAttribute("placeholder")||"";el.placeholder=isEn?(en[el.dataset.i18nPlaceholder]||el.dataset.zhPlaceholder):el.dataset.zhPlaceholder});$("#generate").textContent=(isEn?en:zh).generate;$("#stop").textContent=(isEn?en:zh).stop;set('.workflow-tab[data-workflow="direct"] b',"直接提示词","Direct prompt");set('.workflow-tab[data-workflow="direct"] small',"创意直接转换为 H3","Turn a brief directly into H3");set('.workflow-tab[data-workflow="script"] b',"剧本工作流","Script workflow");set('.workflow-tab[data-workflow="script"] small',"先写剧本，确认后转 H3","Draft and approve a script first");set('.mode[data-mode="Hybrid"] small',"关键帧＋参考媒体＋声音","Keyframes + reference media + audio");set("#manageRoles","管理用途选项","Manage reference types");set("#clearImages","清空","Clear");set("#clearAudios","清空声音","Clear audio");set("#generateScript","生成分段剧本","Generate segmented script");set("#stopScript","停止","Stop");set("#copyScript","复制剧本","Copy script");set("#downloadScript","下载剧本","Download script");set("#confirmScript","✓ 确认剧本并转换为 H3 提示词","✓ Approve script and convert to H3 prompt");if($("#idea"))$("#idea").placeholder=isEn?"Describe the scene, characters, actions, dialogue, style and sound. Type @ to select a Picture reference.":"描述场景、人物、动作、对白、风格及音效。输入 @ 可选择 Picture 参考图。";if($("#scriptBrief"))$("#scriptBrief").placeholder=isEn?"Enter the story, ad requirements, dialogue, or plot goal. Type @ to select a Picture reference.":"输入故事、广告需求、人物对白、情节目标……输入 @ 可以选择 Picture 参考图。";$("#modeNote").textContent=(isEn?notesEn:notes)[mode];updateUploadText();renderTemplates();renderImages();renderAudios();renderScriptReferencePicker()}
function applySize(){const [w,h]=ratios[ratio][$("#quality").value];$("#width").value=w;$("#height").value=h}
function setWorkflow(v){workflow=v;$$('.workflow-tab').forEach(x=>x.classList.toggle('active',x.dataset.workflow===v));$("#scriptWorkflow").classList.toggle("hidden",v!=="script");if(v==="script")$("#scriptWorkflow").scrollIntoView({behavior:"smooth",block:"nearest"})}
$$('.workflow-tab').forEach(b=>b.onclick=()=>setWorkflow(b.dataset.workflow));
Object.keys(ratios).forEach(r=>{const b=document.createElement("button");b.className="ratio"+(r===ratio?" active":"");b.textContent=r;b.onclick=()=>{ratio=r;$$('.ratio').forEach(x=>x.classList.toggle('active',x.textContent===r));applySize();validateConfig()};$("#ratioGrid").appendChild(b)});applySize();$("#quality").onchange=applySize;
$$('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function setMode(v){mode=v;$$('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===v));$("#modeNote").textContent=(uiLang==="en"?notesEn:notes)[v];$("#uploadSection").classList.toggle("hidden",v==="T2VA");$("#audioReferenceSection").classList.toggle("hidden",v!=="Hybrid");if(v==="T2VA"){images=[];audios=[];renderImages();renderAudios()}updateUploadText();validateConfig()}
function updateUploadText(){const zhMap={I2VA:["首帧参考图","第一张为0秒首帧，可附加风格参考"],FL2VA:["首帧与尾帧","必须正好2张：首帧、尾帧"],L2VA:["尾帧参考图","第一张为视频最终画面"],Ref2VA:["完整参考图片","人物、产品、场景、风格等，最多12张"],Hybrid:["关键帧与参考图片","把图片用途设为首帧关键帧、尾帧关键帧或普通参考；还可添加声音"]},enMap={I2VA:["First-frame reference","Picture 1 is the frame at 0 seconds; optional style references may follow"],FL2VA:["First and last frames","Exactly two images: first frame, then last frame"],L2VA:["Last-frame reference","Picture 1 is the final video frame"],Ref2VA:["Complete reference images","Characters, products, scenes, and styles; up to 12 images"],Hybrid:["Keyframes and references","Assign first/last keyframes or regular references; audio references are also supported"]},map=uiLang==="en"?enMap:zhMap;if(map[mode]){$("#uploadTitle").textContent=map[mode][0];$("#uploadHelp").textContent=map[mode][1]}}
function total(){const t=(+$("#segmentCount").value||0)*(+$("#segmentSeconds").value||0);$("#totalSeconds").textContent=t.toFixed(Number.isInteger(t)?0:1);validateConfig()}$("#segmentCount").oninput=total;$("#segmentSeconds").oninput=total;
const drop=$("#dropzone"),input=$("#imageInput");drop.ondragover=e=>{e.preventDefault();drop.classList.add("drag")};drop.ondragleave=()=>drop.classList.remove("drag");drop.ondrop=e=>{e.preventDefault();drop.classList.remove("drag");addFiles([...e.dataTransfer.files])};input.onchange=()=>addFiles([...input.files]);
function referenceRoles(){return JSON.parse(localStorage.getItem("h3.referenceRoles")||'["人物参考","产品参考","场景参考","风格参考"]')}
function saveReferenceRoles(v){localStorage.setItem("h3.referenceRoles",JSON.stringify(v))}
function roleForIndex(i){if(mode==="FL2VA")return i===0?"首帧画面":"尾帧画面";if(mode==="I2VA")return i===0?"首帧画面":"人物参考";if(mode==="L2VA")return i===0?"尾帧画面":"人物参考";if(mode==="Hybrid")return i===0?"首帧关键帧":"人物参考";return referenceRoles()[i%Math.max(referenceRoles().length,1)]||"视觉参考"}
function addFiles(files){files.filter(f=>f.type.startsWith("image/")).slice(0,12-images.length).forEach(file=>{const r=new FileReader();r.onload=()=>{images.push({name:file.name,data:r.result,type:roleForIndex(images.length),description:""});renderImages();validateConfig()};r.readAsDataURL(file)});input.value=""}
function normalizedImage(item,i){if(!item.type){const legacy=item.role||roleForIndex(i),parts=legacy.split(/\s*[-:：]\s*/,2);item.type=referenceRoles().includes(parts[0])?parts[0]:roleForIndex(i);item.description=parts.length>1?parts[1]:(referenceRoles().includes(legacy)?"":legacy)}if(item.description===undefined)item.description="";return item}
function imageRoleText(item,i){normalizedImage(item,i);return `${item.type}${item.description?`: ${item.description}`:""}`}
function roleOptions(selected){const base=[...(mode==="Hybrid"?["首帧关键帧","尾帧关键帧"]:[]),...referenceRoles()],labels={"首帧关键帧":"First-frame keyframe","尾帧关键帧":"Last-frame keyframe","人物参考":"Character reference","产品参考":"Product reference","场景参考":"Scene reference","风格参考":"Style reference","LOGO参考":"Logo reference","服装参考":"Wardrobe reference","道具参考":"Prop reference","视觉参考":"Visual reference"};if(selected&&!base.includes(selected))base.push(selected);return [...new Set(base)].map(x=>`<option value="${escapeHtml(x)}"${x===selected?' selected':''}>${escapeHtml(uiLang==="en"?(labels[x]||x):x)}</option>`).join('')}
function renderImages(){const box=$("#previews");box.innerHTML="";images.forEach((raw,i)=>{const item=normalizedImage(raw,i),el=document.createElement("article");el.className="preview reference-card";el.innerHTML=`<div class="picture-media"><button class="picture-number" data-copy-label="${i}">Picture ${i+1}</button><img src="${item.data}" alt="Picture ${i+1}"></div><div class="reference-fields"><select class="reference-type" aria-label="Picture ${i+1} 用途">${roleOptions(item.type)}</select><input class="reference-description" value="${escapeHtml(item.description)}" placeholder="具体说明，例如：华人女销售、店外、LOGO"></div><div class="reference-tools"><button data-view="${i}">查看</button><button data-copy="${i}">复制图片</button><label class="replace-button">替换<input type="file" accept="image/*" data-replace="${i}"></label><button class="danger-button" data-delete="${i}">删除</button></div>`;el.querySelector(".reference-type").onchange=e=>{item.type=e.target.value;renderScriptReferencePicker();validateConfig()};el.querySelector(".reference-description").oninput=e=>{item.description=e.target.value;renderScriptReferencePicker()};el.querySelector("img").onclick=()=>openImagePreview(i);box.appendChild(el)});box.onclick=async e=>{const view=e.target.dataset.view,copy=e.target.dataset.copy,del=e.target.dataset.delete,label=e.target.dataset.copyLabel;if(view!==undefined)openImagePreview(+view);if(copy!==undefined)await copyImage(+copy);if(label!==undefined){await navigator.clipboard.writeText(`Picture ${+label+1}`);toast(`已复制 Picture ${+label+1} 编号`)}if(del!==undefined){images.splice(+del,1);renderImages();validateConfig();toast("参考图已删除，Picture 编号已自动更新")}};box.onchange=e=>{const idx=e.target.dataset.replace;if(idx===undefined||!e.target.files?.[0])return;const file=e.target.files[0],r=new FileReader();r.onload=()=>{images[+idx].data=r.result;images[+idx].name=file.name;renderImages();toast(`Picture ${+idx+1} 已替换`)};r.readAsDataURL(file)};renderScriptReferencePicker()}
let previewImageIndex=0;
function openImagePreview(i){previewImageIndex=i;const item=normalizedImage(images[i],i);$("#previewPictureLabel").textContent=`Picture ${i+1}`;$("#previewPictureInfo").textContent=imageRoleText(item,i);$("#previewLargeImage").src=item.data;$("#imagePreviewDialog").showModal()}
async function imageAsPng(data){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext("2d").drawImage(img,0,0);c.toBlob(b=>b?resolve(b):reject(Error("PNG conversion failed")),"image/png")};img.onerror=reject;img.src=data})}
async function copyImage(i){try{const blob=await imageAsPng(images[i].data);await navigator.clipboard.write([new ClipboardItem({"image/png":blob})]);toast(`Picture ${i+1} 图片已复制`)}catch{await navigator.clipboard.writeText(images[i].data);toast(`Picture ${i+1} 已复制为图片数据`)}}
$("#copyPreviewImage").onclick=()=>copyImage(previewImageIndex);$("#clearImages").onclick=()=>{images=[];renderImages();validateConfig()};
function insertPictureMention(i,replaceAt=false,inputSelector="#scriptBrief",menuSelector="#pictureMentionMenu"){const el=$(inputSelector),tag=`<Picture ${i+1}>`,start=el.selectionStart,end=el.selectionEnd,before=el.value.slice(0,start),after=el.value.slice(end);let cut=start;if(replaceAt){const match=before.match(/@[^@\s]*$/);if(match)cut=start-match[0].length}const prefix=el.value.slice(0,cut);el.value=prefix+tag+" "+after;el.focus();el.selectionStart=el.selectionEnd=prefix.length+tag.length+1;$(menuSelector).classList.add("hidden");updateReferenceHighlights()}
function referenceChipHtml(x,i,value){const used=new RegExp(`<Picture\\s+${i+1}>`,"i").test(value);return `<span class="reference-mention-chip ${used?"is-used":""}"><button class="reference-chip-main" data-view-reference="${i}" title="${used?"已引用；点击查看大图":"点击查看参考图"}"><img src="${x.data}" alt=""><b>Picture ${i+1}</b><small>${escapeHtml(imageRoleText(x,i))}</small></button><button class="reference-chip-add" data-insert-reference="${i}" title="插入到光标位置">＋</button><span class="reference-hover-preview"><img src="${x.data}" alt="Picture ${i+1}"><strong>Picture ${i+1}</strong><small>${escapeHtml(imageRoleText(x,i))}</small></span></span>`}
function renderReferenceChipBar(containerSelector,inputSelector){const box=$(containerSelector);if(!box)return;const value=$(inputSelector).value;if(!images.length){box.innerHTML=`<small>${uiLang==="en"?"Upload images, then type @ to reference and preview":"上传参考图后，可输入 @ 选择并预览"}</small>`;return}box.innerHTML=images.map((x,i)=>referenceChipHtml(x,i,value)).join("");box.onclick=e=>{const view=e.target.closest('[data-view-reference]'),add=e.target.closest('[data-insert-reference]');if(view)openImagePreview(+view.dataset.viewReference);if(add){insertPictureMention(+add.dataset.insertReference,false,inputSelector,inputSelector==="#idea"?"#ideaMentionMenu":"#pictureMentionMenu");updateReferenceHighlights()}}}
function updateReferenceHighlights(){renderReferenceChipBar("#scriptReferenceChips","#scriptBrief");renderReferenceChipBar("#ideaReferenceChips","#idea");renderInlineMentionOverlay("#scriptBrief");renderInlineMentionOverlay("#idea")}
function inlinePictureTooltip(){let tip=$("#inlinePictureTooltip");if(!tip){tip=document.createElement("div");tip.id="inlinePictureTooltip";tip.className="inline-picture-floating hidden";document.body.appendChild(tip)}return tip}
function showInlinePictureTooltip(token){const idx=+token.dataset.inlinePicture,item=images[idx];if(!item)return;const tip=inlinePictureTooltip(),rect=token.getBoundingClientRect();tip.innerHTML=`<img src="${item.data}" alt="Picture ${idx+1}"><b>Picture ${idx+1}</b><small>${escapeHtml(imageRoleText(item,idx))}</small>`;tip.classList.remove("hidden");const width=250,left=Math.min(window.innerWidth-width-12,Math.max(12,rect.left-70)),height=tip.offsetHeight,top=rect.bottom+10+height<window.innerHeight?rect.bottom+10:Math.max(12,rect.top-height-10);tip.style.left=`${left}px`;tip.style.top=`${top}px`}
function renderInlineMentionOverlay(inputSelector){const input=$(inputSelector),wrap=input.closest(".mention-wrap");if(!wrap)return;let layer=wrap.querySelector(".mention-highlight-layer"),content;if(!layer){layer=document.createElement("div");layer.className="mention-highlight-layer";layer.setAttribute("aria-hidden","true");content=document.createElement("div");content.className="mention-highlight-content";layer.appendChild(content);wrap.insertBefore(layer,wrap.querySelector(".mention-menu"));layer.onclick=e=>{const token=e.target.closest("[data-inline-picture]");if(token){e.preventDefault();e.stopPropagation();inlinePictureTooltip().classList.add("hidden");openImagePreview(+token.dataset.inlinePicture)}};layer.onpointerover=e=>{const token=e.target.closest("[data-inline-picture]");if(token)showInlinePictureTooltip(token)};layer.onpointerout=e=>{const token=e.target.closest("[data-inline-picture]");if(token&&!token.contains(e.relatedTarget))inlinePictureTooltip().classList.add("hidden")}}else content=layer.firstElementChild;const style=getComputedStyle(input);layer.style.width=`${input.clientWidth}px`;layer.style.height=`${input.clientHeight}px`;for(const prop of ["fontFamily","fontSize","fontWeight","fontStyle","letterSpacing","lineHeight","textAlign","textIndent","textTransform","wordSpacing","tabSize"])content.style[prop]=style[prop];const source=input.value;let html="",last=0;for(const match of source.matchAll(/<Picture\s+(\d+)>/gi)){html+=escapeHtml(source.slice(last,match.index));const idx=Number(match[1])-1,item=images[idx];html+=item?`<span class="inline-picture-token" data-inline-picture="${idx}">${escapeHtml(match[0])}</span>`:`<span class="inline-picture-token missing">${escapeHtml(match[0])}</span>`;last=match.index+match[0].length}html+=escapeHtml(source.slice(last));content.innerHTML=html+"\n";content.style.transform=`translate(${-input.scrollLeft}px,${-input.scrollTop}px)`}
function renderScriptReferencePicker(){const menus=[$("#pictureMentionMenu"),$("#ideaMentionMenu")],noImages=uiLang==="en"?"No reference images yet":"还没有参考图";updateReferenceHighlights();if(!images.length){menus.forEach(menu=>menu.innerHTML=`<small>${noImages}</small>`);return}const html=images.map((x,i)=>`<button data-mention-picture="${i}"><img src="${x.data}" alt=""><span><b>Picture ${i+1}</b><small>${escapeHtml(imageRoleText(x,i))}</small></span></button>`).join('');menus.forEach(menu=>menu.innerHTML=html);$("#pictureMentionMenu").onclick=e=>{const b=e.target.closest('[data-mention-picture]');if(b){insertPictureMention(+b.dataset.mentionPicture,true,"#scriptBrief","#pictureMentionMenu");updateReferenceHighlights()}};$("#ideaMentionMenu").onclick=e=>{const b=e.target.closest('[data-mention-picture]');if(b){insertPictureMention(+b.dataset.mentionPicture,true,"#idea","#ideaMentionMenu");updateReferenceHighlights()}}}
function bindPictureMentions(inputSelector,menuSelector){const input=$(inputSelector);input.addEventListener("input",e=>{const before=e.target.value.slice(0,e.target.selectionStart);$(menuSelector).classList.toggle("hidden",!before.match(/@[^@\s]*$/)||!images.length);updateReferenceHighlights()});input.addEventListener("scroll",()=>renderInlineMentionOverlay(inputSelector));input.addEventListener("keydown",e=>{if(e.key==="Escape")$(menuSelector).classList.add("hidden")});renderInlineMentionOverlay(inputSelector)}
bindPictureMentions("#scriptBrief","#pictureMentionMenu");bindPictureMentions("#idea","#ideaMentionMenu");
function renderAudios(){const box=$("#audioList"),isEn=uiLang==="en";box.innerHTML=audios.map((x,i)=>`<div class="audio-card"><span class="audio-number">Audio ${i+1}</span><div><b>${escapeHtml(x.name)}</b><input value="${escapeHtml(x.role||'声音/节奏参考')}" data-audio-role="${i}" placeholder="${isEn?'Describe its purpose':'说明用途'}"></div><button data-audio-delete="${i}">${isEn?'Delete':'删除'}</button></div>`).join('')||`<small>${isEn?'No audio added. Hybrid supports drive_audio or up to 3 independent Audio references.':'尚未添加声音。Hybrid 可使用 drive_audio 或最多3个独立参考 Audio。'}</small>`;box.oninput=e=>{const i=e.target.dataset.audioRole;if(i!==undefined)audios[+i].role=e.target.value};box.onclick=e=>{const i=e.target.dataset.audioDelete;if(i!==undefined){audios.splice(+i,1);renderAudios();validateConfig()}}}
$("#audioInput").onchange=e=>{[...e.target.files].filter(f=>f.type.startsWith('audio/')).slice(0,3-audios.length).forEach(file=>{const r=new FileReader();r.onload=()=>{audios.push({name:file.name,type:file.type,data:r.result,role:"声音/节奏参考"});renderAudios();validateConfig()};r.readAsDataURL(file)});e.target.value=""};$("#clearAudios").onclick=()=>{audios=[];renderAudios();validateConfig()};
function renderRoleManager(){const roles=referenceRoles();$("#roleList").innerHTML=roles.map((x,i)=>`<div class="role-chip"><span>${escapeHtml(x)}</span><button data-role-edit="${i}">编辑</button><button data-role-delete="${i}">删除</button></div>`).join('')||'<small>暂无用途选项，请添加一个。</small>';$("#roleList").onclick=e=>{const roles=referenceRoles(),edit=e.target.dataset.roleEdit,del=e.target.dataset.roleDelete;if(edit!==undefined){const next=prompt("修改用途名称",roles[+edit]);if(next?.trim()){const old=roles[+edit];roles[+edit]=next.trim();images.forEach(x=>{if(x.type===old)x.type=next.trim()});saveReferenceRoles(roles);renderRoleManager();renderImages()}}if(del!==undefined){const removed=roles.splice(+del,1)[0];saveReferenceRoles(roles);images.forEach(x=>{if(x.type===removed)x.type=roles[0]||"视觉参考"});renderRoleManager();renderImages()}}}
$("#manageRoles").onclick=()=>{$("#roleManager").classList.toggle("hidden");renderRoleManager()};$("#addRole").onclick=()=>{const v=$("#newRoleName").value.trim();if(!v)return;const roles=referenceRoles();if(!roles.includes(v)){roles.push(v);saveReferenceRoles(roles)}$("#newRoleName").value="";renderRoleManager();renderImages();toast("用途选项已添加")};
function configError(){if(!$("#idea").value.trim())return "请输入创意内容";if(mode==="T2VA"&&(images.length||audios.length))return "T2VA不能上传参考媒体";if(["I2VA","L2VA","Ref2VA"].includes(mode)&&!images.length)return `${mode}至少需要1张参考图`;if(mode==="FL2VA"&&images.length!==2)return "FL2VA必须正好上传2张图";if(mode==="Hybrid"){if(images.length>9)return "你安装的T8 Hybrid节点最多支持9张Picture";const keyframes=images.filter((x,i)=>{const t=normalizedImage(x,i).type;return /首帧|尾帧|first frame|last frame/i.test(t)}),refs=images.filter((x,i)=>{const t=normalizedImage(x,i).type;return !/首帧|尾帧|first frame|last frame/i.test(t)});if(!keyframes.length)return "HYBRID至少需要1张标记为首帧或尾帧的关键帧";if(!refs.length&&!audios.length)return "HYBRID除关键帧外，还需要参考图或参考声音"}if(!$("#model").value)return "请选择Ollama模型";return ""}
function validateConfig(){let msg=configError();const el=$("#validation");if(uiLang==="en")msg=msg.replace("请输入创意内容","Enter a creative brief").replace("请选择Ollama模型","Select an Ollama model").replace("至少需要1张参考图"," requires at least one reference image").replace("必须正好上传2张图"," requires exactly two images");if(msg){el.className="validation warn";el.textContent=msg}else{el.className="validation good";el.textContent=uiLang==="en"?`Valid · ${mode} · ${$("#segmentCount").value} segment(s) × ${$("#segmentSeconds").value}s · ${ratio}`:`配置有效 · ${mode} · ${$("#segmentCount").value}段 × ${$("#segmentSeconds").value}秒 · ${ratio}`}}
function selectedSkills(){const ids=new Set(selectedSkillIds);return allSkills().filter(x=>ids.has(x.id)).slice(0,3)}
function payload(){return{workflow,mode,model:$("#model").value,backend:backendType(),baseUrl:endpoint(),apiKey:settings.apiKey||"",ollamaUrl:endpoint(),idea:$("#idea").value,scriptBrief:$("#scriptBrief").value,scriptGenre:$("#scriptGenre").value,scriptAudience:$("#scriptAudience").value,scriptTone:$("#scriptTone").value,scriptOutputLanguage:$("#scriptOutputLanguage").value,promptOutputLanguage:$("#promptOutputLanguage").value,scriptOutput:$("#scriptResult").value,selectedSkillIds:[...selectedSkillIds],selectedSkills:selectedSkills().map(x=>({name:x.name,description:x.description,instructions:x.instructions})),images:images.map(x=>x.data),imageRoles:images.map((x,i)=>imageRoleText(x,i)),imageTypes:images.map((x,i)=>normalizedImage(x,i).type),imageDescriptions:images.map((x,i)=>normalizedImage(x,i).description),audioNames:audios.map(x=>x.name),audioRoles:audios.map(x=>x.role||"声音/节奏参考"),audioMode:$("#audioMode").value,audioDirection:$("#audioDirection").value,aspectRatio:ratio,width:+$("#width").value,height:+$("#height").value,segmentCount:+$("#segmentCount").value,segmentSeconds:+$("#segmentSeconds").value,language:$("#language").value,style:$("#style").value,music:$("#music").value,sound:$("#sound").value,negative:$("#negative").value,temperature:+$("#temperature").value,context:+$("#context").value}}
async function health(){try{const r=await fetch(api('/api/health')),d=await r.json();$("#status").className="status "+(d.ok?"ok":"bad");$("#status").lastElementChild.textContent=d.ok?(uiLang==="en"?`${backendType()} online · ${d.models} models`:`${backendType()} 在线 · ${d.models}个模型`):(uiLang==="en"?"Ollama disconnected":"Ollama未连接");$("#footerEndpoint").textContent=endpoint().replace(/^https?:\/\//,'');return d.ok}catch{$("#status").className="status bad";$("#status").lastElementChild.textContent="服务异常";return false}}
async function models(){const sel=$("#model"),remember=settings.lastModel;sel.innerHTML='<option value="">正在读取……</option>';try{const r=await fetch(api('/api/models')),d=await r.json();if(!r.ok)throw Error(d.error);sel.innerHTML=d.models.length?d.models.map(m=>`<option value="${escapeHtml(m)}">${escapeHtml(m)}</option>`).join(''):'<option value="">没有发现模型</option>';if(remember&&d.models.includes(remember))sel.value=remember;await modelInfo()}catch(e){sel.innerHTML='<option value="">无法连接Ollama</option>';$("#validation").className="validation error";$("#validation").textContent=e.message;$("#ollamaGuide").innerHTML='<b>Ollama 离线排查</b><ol><li>启动 Ollama 应用或运行 <code>ollama serve</code></li><li>确认地址通常为 http://127.0.0.1:11434</li><li>参考图模式请安装多模态模型，例如 <code>ollama pull qwen3.5:9b</code></li></ol>';$("#settingsDialog").showModal()}validateConfig()}
async function modelInfo(){const m=$("#model").value;if(!m)return;settings.lastModel=m;saveSettingsLocal();try{const r=await fetch(api('/api/model-info')+'&model='+encodeURIComponent(m)),d=await r.json();const cap=$("#capability");cap.className="capability "+(d.vision?"good":"warn");cap.textContent=d.vision?`✓ 多模态视觉 · ${d.family||''} ${d.parameterSize||''}`:`⚠ 未检测到视觉能力；${mode==="T2VA"?'T2VA可用':'参考图模式可能无效'}`}catch{$("#capability").textContent="无法读取模型能力"}}
$("#model").onchange=()=>{modelInfo();validateConfig()};$("#refreshModels").onclick=()=>{health();models()};
async function releaseVram(silent=false){const model=$("#model").value;if(!model){if(!silent)toast("请先选择要卸载的模型");return false}try{const r=await fetch("/api/unload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({backend:backendType(),baseUrl:endpoint(),apiKey:settings.apiKey||"",model})}),d=await r.json();if(!r.ok)throw Error(d.error||"卸载失败");$("#capability").textContent="✓ 模型已从显存卸载";if(!silent)toast(`${backendType()} 模型已卸载，显存正在释放`);return true}catch(e){if(!silent)toast(`释放显存失败：${e.message}`);return false}}
$("#releaseVram").onclick=()=>releaseVram(false);
function parseSegments(){segments=[];const re=/===\s*Segment\s+\d+[^=]*===/gi,matches=[...fullOutput.matchAll(re)];if(matches.length){matches.forEach((m,i)=>segments.push(fullOutput.slice(m.index,matches[i+1]?.index??fullOutput.length).trim()))}renderSegmentTabs()}
function renderSegmentTabs(){const box=$("#segmentTabs");box.innerHTML="";box.classList.toggle("hidden",!segments.length);$("#copySegment").classList.toggle("hidden",!segments.length);const all=document.createElement("button");all.textContent="全部";all.className=activeSegment<0?"active":"";all.onclick=()=>showSegment(-1);box.appendChild(all);segments.forEach((_,i)=>{const b=document.createElement("button");b.textContent=`第 ${i+1} 段`;b.className=activeSegment===i?"active":"";b.onclick=()=>showSegment(i);box.appendChild(b)});$("#copySegment").disabled=!segments.length}
function showSegment(i){activeSegment=i;$("#result").value=i<0?fullOutput:segments[i];renderSegmentTabs()}
async function generate(){const err=configError();if(err){validateConfig();return}aborter=new AbortController();fullOutput="";segments=[];activeSegment=-1;$("#result").value="";$("#loading").classList.remove("hidden");$("#generate").disabled=true;$("#stop").classList.remove("hidden");$("#stop").disabled=false;$("#resultMeta").textContent="正在流式生成并校验 H3 格式……";const p=payload();let formatWarnings=[],autoNormalized=false;try{const r=await fetch('/api/generate-stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p),signal:aborter.signal});if(!r.ok){const e=await r.text();throw Error(e)}const reader=r.body.getReader(),decoder=new TextDecoder();let buf="";while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop();for(const line of lines){if(!line.trim())continue;const d=JSON.parse(line);const piece=d.text||d.chunk||"";if(piece){fullOutput+=piece;$("#result").value=fullOutput;$("#result").scrollTop=$("#result").scrollHeight}if(d.type==="done"){formatWarnings=d.warnings||[];if(typeof d.final==="string"&&d.final){autoNormalized=d.final.trim()!==fullOutput.trim();fullOutput=d.final;$("#result").value=fullOutput}}if(d.type==="error"||d.error)throw Error(d.error)}}parseSegments();$("#resultMeta").textContent=`完成 · ${segments.length||1} 个提示词段落${autoNormalized?" · 已自动规范 H3 格式":""}${formatWarnings.length?` · ${formatWarnings.length}项格式提醒`:""}`;await dbPut("history",{id:Date.now(),createdAt:new Date().toISOString(),name:$("#projectName").value||"未命名",config:p,output:fullOutput});toast(formatWarnings.length?"生成完成；仍有少量格式提醒，请检查结果":"生成完成并已通过 H3 格式整理")}catch(e){$("#resultMeta").textContent=e.name==="AbortError"?"已停止":"生成失败";if(e.name!=="AbortError"){$("#validation").className="validation error";$("#validation").textContent=e.message}}finally{$("#loading").classList.add("hidden");$("#generate").disabled=false;$("#stop").classList.add("hidden");$("#stop").disabled=true;if(settings.autoUnload)await releaseVram(true);aborter=null}}
async function generateScript(){const brief=$("#scriptBrief").value.trim();if(!brief){toast("请先输入剧本创意");$("#scriptBrief").focus();return}if(!$("#model").value){toast("请选择 Ollama 模型");return}scriptAborter=new AbortController();$("#scriptResult").value="";$("#generateScript").disabled=true;$("#stopScript").classList.remove("hidden");$("#scriptStatus").textContent="正在由本地模型策划分段剧本……";const p=payload();try{const r=await fetch('/api/script-stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p),signal:scriptAborter.signal});if(!r.ok)throw Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buf="";while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop();for(const line of lines){if(!line.trim())continue;const d=JSON.parse(line);if(d.text){$("#scriptResult").value+=d.text;$("#scriptResult").scrollTop=$("#scriptResult").scrollHeight}if(d.type==="error"||d.error)throw Error(d.error)}}const count=($("#scriptResult").value.match(/===\s*Segment\s+\d+/gi)||[]).length;$("#scriptStatus").textContent=`剧本完成 · ${count||$("#segmentCount").value} 段 · 可直接编辑，确认后再转换`;toast("分段剧本已生成，请检查和修改")}catch(e){$("#scriptStatus").textContent=e.name==="AbortError"?"剧本生成已停止":`剧本生成失败：${e.message}`}finally{$("#generateScript").disabled=false;$("#stopScript").classList.add("hidden");scriptAborter=null}}
function confirmScript(){const script=$("#scriptResult").value.trim();if(!script){toast("还没有可转换的剧本");return}$("#idea").value=`以下是已经人工确认的分段剧本。请严格保留人物、场景、动作连续性、Picture 编号和原始对白，将每个 Segment 分别转换为独立且完整的 MiniMax H3 ${mode} 提示词：\n\n${script}`;updateReferenceHighlights();validateConfig();$("#idea").scrollIntoView({behavior:"smooth",block:"center"});toast("剧本已送入 H3 转换区，可继续编辑或点击生成")}
$("#generateScript").onclick=generateScript;$("#stopScript").onclick=()=>scriptAborter?.abort();$("#confirmScript").onclick=confirmScript;$("#copyScript").onclick=()=>navigator.clipboard.writeText($("#scriptResult").value).then(()=>toast("剧本已复制"));$("#downloadScript").onclick=()=>download(`${safeName($("#projectName").value||"video-script")}-script.txt`,$("#scriptResult").value,'text/plain');
$("#generate").onclick=generate;$("#stop").onclick=()=>aborter?.abort();$("#copy").onclick=()=>navigator.clipboard.writeText($("#result").value).then(()=>toast("已复制"));$("#copySegment").onclick=()=>navigator.clipboard.writeText(activeSegment<0?(segments[0]||fullOutput):(segments[activeSegment]||fullOutput)).then(()=>toast("当前分段已复制"));$("#download").onclick=()=>download(`${safeName($("#projectName").value||"H3-prompt")}.txt`,fullOutput,'text/plain');
function safeName(s){return s.replace(/[\\/:*?"<>|]/g,'_')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function snapshot(){return{id:Date.now(),name:$("#projectName").value||"未命名项目",updatedAt:new Date().toISOString(),config:payload(),images,audios,output:fullOutput}}
function applySnapshot(x){const c=x.config||x;$("#projectName").value=x.name||"未命名项目";setMode(c.mode||"T2VA");setWorkflow(c.workflow||"direct");$("#idea").value=c.idea||"";$("#scriptBrief").value=c.scriptBrief||"";$("#scriptGenre").value=c.scriptGenre||"广告短片";$("#scriptAudience").value=c.scriptAudience||"";$("#scriptTone").value=c.scriptTone||"";$("#scriptResult").value=c.scriptOutput||"";images=x.images||((c.images||[]).map((data,i)=>({data,name:`reference-${i+1}`,type:(c.imageTypes||[])[i],description:(c.imageDescriptions||[])[i],role:(c.imageRoles||[])[i]||"视觉参考"})));audios=x.audios||((c.audioNames||[]).map((name,i)=>({name,role:(c.audioRoles||[])[i]||"声音/节奏参考",data:""})));renderImages();renderAudios();ratio=c.aspectRatio||"16:9";$$('.ratio').forEach(b=>b.classList.toggle('active',b.textContent===ratio));for(const id of ['width','height','segmentCount','segmentSeconds','language','promptOutputLanguage','scriptOutputLanguage','style','music','sound','negative','temperature','context','audioMode','audioDirection'])if(c[id]!==undefined&&$('#'+id))$('#'+id).value=c[id];fullOutput=x.output||"";$("#result").value=fullOutput;parseSegments();total();if(c.model){settings.lastModel=c.model;saveSettingsLocal();models()}validateConfig()}
$("#saveProject").onclick=async()=>{const s=snapshot();await dbPut("projects",s);toast("项目已保存")};$("#newProject").onclick=()=>{applySnapshot({name:"未命名项目",config:{mode:"T2VA",idea:"",aspectRatio:"16:9",segmentCount:1,segmentSeconds:5,language:"自动识别",promptOutputLanguage:"en",scriptOutputLanguage:"zh",style:"",music:"",sound:"",negative:"",temperature:.35,context:16384},images:[],output:""})};
$("#exportConfig").onclick=()=>download(`${safeName($("#projectName").value||"h3-config")}.json`,JSON.stringify(snapshot(),null,2),'application/json');$("#importConfig").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{applySnapshot(JSON.parse(r.result));toast("配置已导入")}catch{toast("配置文件无效")}};r.readAsText(f);e.target.value=""};
function openDrawer(panel){$("#workspaceDrawer").classList.remove("hidden");$("#historyPanel").classList.toggle("hidden",panel!=="history");$("#templatePanel").classList.toggle("hidden",panel!=="template");$("#skillPanel").classList.toggle("hidden",panel!=="skill");const titles={history:"项目与生成历史",template:"模板管理",skill:"创意增强技能库"},helps={history:"点击记录即可载入；可随时删除不需要的记录。",template:"可以新增、选择、编辑、替换和删除所有模板。",skill:"可多选 Skill；支持新增、编辑、删除，以及导入本地 SKILL.md。"};$("#drawerTitle").textContent=titles[panel];$("#drawerHelp").textContent=helps[panel];$("#workspaceDrawer").scrollIntoView({behavior:"smooth",block:"start"})}
async function showHistory(){openDrawer("history");const projects=(await dbAll("projects")).sort((a,b)=>b.id-a.id),history=(await dbAll("history")).sort((a,b)=>b.id-a.id).slice(0,50);$("#historyList").innerHTML=[...projects.map(x=>listRow(x,"项目","projects")),...history.map(x=>listRow(x,"历史","history"))].join('')||'<p>暂无记录</p>';$("#historyList").onclick=async e=>{const id=+e.target.dataset.id,store=e.target.dataset.store;if(!id||!store)return;if(e.target.dataset.action==="delete"){await dbDelete(store,id);showHistory();return}const all=await dbAll(store),x=all.find(v=>v.id===id);if(x){applySnapshot(store==="history"?{name:x.name,config:x.config,images:(x.config.images||[]).map((d,i)=>({data:d,type:x.config.imageTypes?.[i],description:x.config.imageDescriptions?.[i],role:x.config.imageRoles?.[i]||"视觉参考"})),output:x.output}:x);toast("记录已载入")}}}
function listRow(x,label,store){return `<div class="list-row"><div><b>${escapeHtml(x.name||"未命名")}</b><small>${label} · ${new Date(x.updatedAt||x.createdAt||x.id).toLocaleString()}</small></div><div><button data-id="${x.id}" data-store="${store}">载入</button><button data-action="delete" data-id="${x.id}" data-store="${store}">删除</button></div></div>`}$("#historyBtn").onclick=showHistory;
function allTemplates(){const raw=localStorage.getItem("h3.templates.v2");if(raw)return JSON.parse(raw);const legacy=JSON.parse(localStorage.getItem("h3.templates")||"[]");return [...builtinTemplates.map(x=>({...x})),...legacy.map(x=>({...x,id:x.id||"template-"+Date.now()}))]}
function saveTemplates(all){localStorage.setItem("h3.templates.v2",JSON.stringify(all))}
let editingTemplateId=null;
function resetTemplateEditor(){$("#templateName").value="";$("#templateIdea").value="";$("#templateStyle").value="";editingTemplateId=null;$("#saveTemplate").textContent="＋ 保存为新模板";$("#cancelTemplateEdit").classList.add("hidden")}
function renderTemplates(){const all=allTemplates(),isEn=uiLang==="en",builtin={cinematic:"Cinematic story",product:"Product ad",action:"Action battle",meme:"Exaggerated meme short"};const selected=$("#templateSelect").value;$("#templateSelect").innerHTML=`<option value="">${isEn?'Choose a template…':'选择模板……'}</option>`+all.map(x=>`<option value="${escapeHtml(x.id)}">${escapeHtml(isEn?(builtin[x.id]||x.name):x.name)}</option>`).join('');if(all.some(x=>x.id===selected))$("#templateSelect").value=selected;$("#templateList").innerHTML=all.map(x=>`<div class="list-row"><div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.idea.slice(0,120))}</small></div><div><button data-use="${x.id}">使用</button><button data-edit="${x.id}">编辑</button><button data-delete="${x.id}">删除</button></div></div>`).join('')||'<p>暂无模板，可以在上方建立。</p>';$("#templateList").onclick=e=>{const all=allTemplates(),use=e.target.dataset.use,edit=e.target.dataset.edit,del=e.target.dataset.delete;if(use){const x=all.find(t=>t.id===use);if(x){$("#templateSelect").value=x.id;applySelectedTemplate();toast("模板已更换并应用")}}if(edit){const x=all.find(t=>t.id===edit);if(x){editingTemplateId=x.id;$("#templateName").value=x.name;$("#templateIdea").value=x.idea;$("#templateStyle").value=x.style||"";$("#saveTemplate").textContent="保存修改";$("#cancelTemplateEdit").classList.remove("hidden");$("#templateName").focus()}}if(del){saveTemplates(all.filter(x=>x.id!==del));if(editingTemplateId===del)resetTemplateEditor();renderTemplates();toast("模板已删除")}}}
function applySelectedTemplate(){const x=allTemplates().find(t=>t.id===$("#templateSelect").value);if(x){$("#idea").value=x.idea;$("#style").value=x.style||"";updateReferenceHighlights();validateConfig()}}
$("#applyTemplate").onclick=applySelectedTemplate;$("#templateBtn").onclick=()=>{openDrawer("template");renderTemplates()};$("#saveTemplate").onclick=()=>{const name=$("#templateName").value.trim(),idea=$("#templateIdea").value.trim(),style=$("#templateStyle").value.trim();if(!name||!idea){toast("请填写模板名称和内容");return}const all=allTemplates(),wasEditing=Boolean(editingTemplateId);if(editingTemplateId){const i=all.findIndex(x=>x.id===editingTemplateId);if(i>=0)all[i]={...all[i],name,idea,style}}else all.push({id:"template-"+Date.now(),name,idea,style});saveTemplates(all);renderTemplates();resetTemplateEditor();toast(wasEditing?"模板修改已保存":"模板已保存")};$("#cancelTemplateEdit").onclick=resetTemplateEditor;$("#useCurrentPrompt").onclick=()=>{$("#templateIdea").value=$("#idea").value;$("#templateStyle").value=$("#style").value;toast("已读取当前提示词内容")};$("#closeDrawer").onclick=()=>$("#workspaceDrawer").classList.add("hidden");
function saveSettingsLocal(){settings.language=uiLang;settings.theme=colorTheme;localStorage.setItem("h3.settings",JSON.stringify(settings))}
function applyTheme(){document.documentElement.dataset.theme=colorTheme;$("#themeBtn").textContent=colorTheme==="dark"?"☀ 日间":"☾ 夜间";$("#themeBtn").title=colorTheme==="dark"?"切换到日间主题":"切换到夜间主题"}
function fillBackendSettings(){const type=$("#backend").value||backendType(),urls=settings.backendUrls||{};$("#backendUrl").value=urls[type]||((type===backendType()&&settings.baseUrl)?settings.baseUrl:backendDefaults[type]);$("#apiKey").value=settings.apiKey||"";$("#autoUnload").checked=Boolean(settings.autoUnload);$("#apiKeyRow").classList.toggle("hidden",type==="ollama")}
$("#backend").onchange=fillBackendSettings;$("#settingsBtn").onclick=()=>{$("#backend").value=backendType();fillBackendSettings();$("#settingsDialog").showModal()};$("#saveSettings").onclick=()=>{const type=$("#backend").value,url=$("#backendUrl").value.trim()||backendDefaults[type];settings.backend=type;settings.baseUrl=url;settings.apiKey=$("#apiKey").value.trim();settings.autoUnload=$("#autoUnload").checked;settings.backendUrls={...(settings.backendUrls||{}),[type]:url};saveSettingsLocal();$("#settingsDialog").close();health();models()};$("#testOllama").onclick=async()=>{const old={backend:settings.backend,baseUrl:settings.baseUrl,apiKey:settings.apiKey};settings.backend=$("#backend").value;settings.baseUrl=$("#backendUrl").value.trim()||backendDefaults[settings.backend];settings.apiKey=$("#apiKey").value.trim();const ok=await health();Object.assign(settings,old);toast(ok?"AI 后端连接成功":"无法连接 AI 后端，请检查地址、服务和 API Key")};$("#langBtn").onclick=()=>{uiLang=uiLang==="zh"?"en":"zh";saveSettingsLocal();applyI18n()};$("#themeBtn").onclick=()=>{colorTheme=colorTheme==="dark"?"light":"dark";applyTheme();saveSettingsLocal()};$("#changelogBtn").onclick=()=>$("#changelogDialog").showModal();
$$('dialog [data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$("#idea").oninput=validateConfig;
$(".changelog")?.insertAdjacentHTML("afterbegin",'<b>v0.5.8</b><ul><li>生成结构严格对齐 h3-prompt-writing 技能规范</li><li>修正 Ref2VA Subject、摘要前缀、保留关系与 Shot 时间格式</li><li>H3 标准英文改为默认推荐输出</li></ul><b>v0.5.7</b><ul><li>剧本工作流新增独立的剧本输出语言选择</li><li>创意内容新增独立的 H3 提示词输出语言选择</li><li>对白语言与说明文字语言分离，固定技术标签保持标准格式</li></ul>');
$(".eyebrow").textContent="LOCAL GENERATION · V0.5.8";$("#promptOutputLanguage").value="en";applyTheme();applyI18n();renderTemplates();renderScriptReferencePicker();renderAudios();setMode("T2VA");$("#projectName").placeholder=(uiLang==="zh"?zh:en).project;$("#backend").value=backendType();fillBackendSettings();health();models();total();




